### PR TITLE
Bobmcc9 patch 1

### PR DESCRIPTION
**Pull request by bobmcc9**
all code from https://github.com/IBM/IBMSAFR-Spark moved across

### CODE REVIEW

**Review by SaPeresi — CHANGES_REQUESTED** [review]
Bob,  I noticed a lot of files that shouldn't be there - most likely, after speaking with Kip, because you don't have a .gitignore file in your local repository.  Can you put one there and repull your request?  Also, I am reviewing the files over the next two days with an eye to looking for the appropriate level of documentation in the files themselves.  Not sure if I will find anything needs fixing but wanted you to know.

**Review by SaPeresi — COMMENTED** [review]
project is misspelled.

**Comment by bobmcc9** [comment]
Based on recent comments which are very very helpful, we should maybe discard this pull. Assess changes changes required and do a repull

**Comment by SaPeresi** [comment]
Agreed Bob - only left it out there so you could review based on the comments.  I believe I can delete the pull request after you have created a new one - just for comparison sake.  Your thoughts?

**Comment by bobmcc9** [comment]
Sounds Like a plan. I have no real knowledge of this repo so need to defer to Kip for his advice on issues you raised

**Comment by bobmcc9** [comment]
This pull request should not be actioned

**Comment by KipTwitchell** [comment]
based as recommended, this is discarded.

**Pull request closed without merging**
